import assert from "node:assert/strict";
import { lastMoveLine, placeDraftError, placeMove, unitPlaceLabel } from "../src/lib/ops/unit-place-rules.ts";

assert.equal(placeMove(null), "create");
assert.equal(placeMove({ status: "ready" }), "move");
assert.equal(placeMove({ status: "assigned" }), "blocked");
assert.equal(unitPlaceLabel({ site: "barn-back", pallet: "g", level: 1, status: "ready" }), "Back · G-L1");
assert.equal(unitPlaceLabel({ site: "barn-front", pallet: "G", level: 1, status: "ready" }), "Front · G-L1");
assert.equal(placeDraftError({ site: "barn-front", pallet: "G" }), "Pick a level.");
assert.equal(placeDraftError({ site: "barn-front", pallet: "G", level: "1" }), null);
assert.equal(unitPlaceLabel({ site: "training", status: "deployed" }), "Training");
assert.equal(unitPlaceLabel({ site: "front-lobby", status: "deployed" }), "Lobby");
assert.equal(unitPlaceLabel({ site: "staging", status: "deployed" }), "Staging area");
assert.equal(unitPlaceLabel({ site: "other", purpose: "parts cage", status: "deployed" }), "parts cage");
assert.equal(placeDraftError({ site: "barn-back", pallet: "" }), "Pick a bay A through P.");
assert.equal(placeDraftError({ site: "" }), "Pick a rack.");
assert.equal(placeDraftError({ site: "other", otherLabel: "  " }), "Other needs a short label.");
assert.equal(placeDraftError({ site: "training" }), null);
assert.equal(lastMoveLine("note\nMoved from Barn · A to Training · ada · today"), "Moved from Barn · A to Training · ada · today");
console.log("unit place ok");
