/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppHandoffRouteImport } from './routes/_app/handoff'
import { Route as AppInstallsRouteImport } from './routes/_app/installs'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppModulesRouteImport } from './routes/_app/modules'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppPmsRouteImport } from './routes/_app/pms'
import { Route as AppRecipesRouteImport } from './routes/_app/recipes'
import { Route as AppServiceRouteImport } from './routes/_app/service'
import { Route as AppTlcRouteImport } from './routes/_app/tlc'
import { Route as AppWarehouseRouteImport } from './routes/_app/warehouse'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppHandoffRoute = AppHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallsRoute = AppInstallsRouteImport.update({
  id: '/installs',
  path: '/installs',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesRoute = AppModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPmsRoute = AppPmsRouteImport.update({
  id: '/pms',
  path: '/pms',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceRoute = AppServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AppRoute,
} as any)
const AppTlcRoute = AppTlcRouteImport.update({
  id: '/tlc',
  path: '/tlc',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehouseRoute = AppWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/handoff': typeof AppHandoffRoute
  '/installs': typeof AppInstallsRoute
  '/locations': typeof AppLocationsRoute
  '/modules': typeof AppModulesRoute
  '/pipeline': typeof AppPipelineRoute
  '/pms': typeof AppPmsRoute
  '/recipes': typeof AppRecipesRoute
  '/service': typeof AppServiceRoute
  '/tlc': typeof AppTlcRoute
  '/warehouse': typeof AppWarehouseRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/handoff': typeof AppHandoffRoute
  '/installs': typeof AppInstallsRoute
  '/locations': typeof AppLocationsRoute
  '/modules': typeof AppModulesRoute
  '/pipeline': typeof AppPipelineRoute
  '/pms': typeof AppPmsRoute
  '/recipes': typeof AppRecipesRoute
  '/service': typeof AppServiceRoute
  '/tlc': typeof AppTlcRoute
  '/warehouse': typeof AppWarehouseRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/handoff': typeof AppHandoffRoute
  '/_app/installs': typeof AppInstallsRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/modules': typeof AppModulesRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/pms': typeof AppPmsRoute
  '/_app/recipes': typeof AppRecipesRoute
  '/_app/service': typeof AppServiceRoute
  '/_app/tlc': typeof AppTlcRoute
  '/_app/warehouse': typeof AppWarehouseRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/handoff'
    | '/installs'
    | '/locations'
    | '/modules'
    | '/pipeline'
    | '/pms'
    | '/recipes'
    | '/service'
    | '/tlc'
    | '/warehouse'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/access'
    | '/handoff'
    | '/installs'
    | '/locations'
    | '/modules'
    | '/pipeline'
    | '/pms'
    | '/recipes'
    | '/service'
    | '/tlc'
    | '/warehouse'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/access'
    | '/_app/handoff'
    | '/_app/installs'
    | '/_app/locations'
    | '/_app/modules'
    | '/_app/pipeline'
    | '/_app/pms'
    | '/_app/recipes'
    | '/_app/service'
    | '/_app/tlc'
    | '/_app/warehouse'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/handoff': {
      id: '/_app/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof AppHandoffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installs': {
      id: '/_app/installs'
      path: '/installs'
      fullPath: '/installs'
      preLoaderRoute: typeof AppInstallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules': {
      id: '/_app/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AppModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pms': {
      id: '/_app/pms'
      path: '/pms'
      fullPath: '/pms'
      preLoaderRoute: typeof AppPmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service': {
      id: '/_app/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof AppServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tlc': {
      id: '/_app/tlc'
      path: '/tlc'
      fullPath: '/tlc'
      preLoaderRoute: typeof AppTlcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouse': {
      id: '/_app/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AppWarehouseRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppHandoffRoute: typeof AppHandoffRoute
  AppInstallsRoute: typeof AppInstallsRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppModulesRoute: typeof AppModulesRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPmsRoute: typeof AppPmsRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppServiceRoute: typeof AppServiceRoute
  AppTlcRoute: typeof AppTlcRoute
  AppWarehouseRoute: typeof AppWarehouseRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppHandoffRoute: AppHandoffRoute,
  AppInstallsRoute: AppInstallsRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppModulesRoute: AppModulesRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPmsRoute: AppPmsRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppServiceRoute: AppServiceRoute,
  AppTlcRoute: AppTlcRoute,
  AppWarehouseRoute: AppWarehouseRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
